### PR TITLE
Added Elastic & Instaclustr

### LINKED ISSUE #41: Add Elastic as Bronze Sponsor
**Actual Behaviour**
Missing Elastic logo 

**Expected Behaviour**
Adding Elastic logo under Bronze Sponsor section

Logo:
elastic-logo-H-full color

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://nishithp.live/summit.fossasia.org)

- Fixes  #41 #45 

## Description / Changes
Hi, I have added Elastic as a bronze Sponsor & Instaclustr as a Silver sponsor.

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
@edenyay Please review

**Comment by jatin2003** [comment]
LGTM

**Comment by kushthedude** [comment]
@mariobehling Please merge

**Comment by hpdang** [comment]
@NishithP2004 this issue was closed by another PR but thank you for your help

**Pull request closed without merging**
