### PR TITLE
Update Hackathon Section 

### LINKED ISSUE #47: Replace block-text section UNESCO Hackathon by Linux Professional Institute Exam Lab
**Actual Behaviour**
The current block-text section UNESCO Hackathon (as in screenshot) is out of date. We need to replace with the new information & link.

Screen Shot 2020-02-04 at 10 42 24

**Expected Behaviour**
Replace block-text section UNESCO Hackathon by Linux Professional Institute Exam Lab

(Title) 
Linux Professional Institute Exam Lab
Saturday March 21, 10:00 - 13:00

(Body) 
Linux Professional Institute is thrilled to be offering exams at a discounted rate
exclusively to FOSSASIA attendees. While at FOSSASIA, write the Linux Essentials for $75
USD, DevOps Tools Engineer for $99 USD, BSD Specialist for $99 USD, LPIC for $99 USD.
Please register in advance. You can provide advance payment by Paypal or credit card (a
choice within the Paypal link). You have the opportunity to take up to 2 exams within this
exam lab. The exam will be presented and provided in English.

Keep the **sign up here** button, but redirect to: https://pretix.eu/lpi.org/9rwwp

Replace the photo on the right with the photo below:
IMG_4009 CR2

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://nishithp.live/summit.fossasia.org)

- Fixes #47 

## Description / Changes
I have updated the block text as per the request.

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by Chaitanyassr** [comment]
unable to open the preview link.Please check ones.

**Comment by NishithP2004** [comment]
> unable to open the preview link.Please check ones.

It's working for me (you may have encountered this issue as the custom domain has a few errors with the SSL certificate)
Please go to advanced settings and click on proceed to site (unsafe)

**Comment by NishithP2004** [comment]
> Screenshot_20200206-075719
> The image is getting displaced in my mobile screen, please check.

I just noticed it , I'll try to fix it . thank you

**Comment by NishithP2004** [comment]
@edenyay Please review

**Comment by NishithP2004** [comment]
> Screenshot_20200206-075719
> The image is getting displaced in my mobile screen, please check.

I have fixed this

**Comment by NishithP2004** [comment]
Screenshot_2020-02-06-16-42-29-250_com android chrome

**Comment by NishithP2004** [comment]
Screenshot_2020-02-06-16-42-29-250_com android chrome

**Comment by Chaitanyassr** [comment]
> > Screenshot_20200206-075719
> > The image is getting displaced in my mobile screen, please check.
> 
> I have fixed this

Have you updated the preview link? Because the image is still getting misplaced in my mobile screen.

**Comment by NishithP2004** [comment]
> > > Screenshot_20200206-075719
> > > The image is getting displaced in my mobile screen, please check.
> > 
> > 
> > I have fixed this
> 
> Have you updated the preview link? Because the image is still getting misplaced in my mobile screen.
Yes I have

**Pull request merged**
