### PR TITLE
Update Hackathon section

### LINKED ISSUE #47: Replace block-text section UNESCO Hackathon by Linux Professional Institute Exam Lab
**Actual Behaviour**
The current block-text section UNESCO Hackathon (as in screenshot) is out of date. We need to replace with the new information & link.

Screen Shot 2020-02-04 at 10 42 24

**Expected Behaviour**
Replace block-text section UNESCO Hackathon by Linux Professional Institute Exam Lab

(Title) 
Linux Professional Institute Exam Lab
Saturday March 21, 10:00 - 13:00

(Body) 
Linux Professional Institute is thrilled to be offering exams at a discounted rate
exclusively to FOSSASIA attendees. While at FOSSASIA, write the Linux Essentials for $75
USD, DevOps Tools Engineer for $99 USD, BSD Specialist for $99 USD, LPIC for $99 USD.
Please register in advance. You can provide advance payment by Paypal or credit card (a
choice within the Paypal link). You have the opportunity to take up to 2 exams within this
exam lab. The exam will be presented and provided in English.

Keep the **sign up here** button, but redirect to: https://pretix.eu/lpi.org/9rwwp

Replace the photo on the right with the photo below:
IMG_4009 CR2

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](http://nishithp.live/summit.fossasia.org/)

- Fixes #47 

## Description / Changes
Hi there, I have made the incomplete changes from the previous PR, thereby fixing the above issue.

### After:
Screenshot (43)

- - - - - - - - - - - -

### CODE REVIEW

**Comment by NishithP2004** [comment]
@edenyay Please review

**Comment by NishithP2004** [comment]
P.S. It works well in mobile view as well.

**Comment by jatin2003** [comment]
It looks good to me as It's working well in mobile view too.

**Comment by edenyay** [comment]
thanks all!

**Pull request merged**
