### PR TITLE
updated year

### LINKED ISSUE #50: year needs to be changed from 2019 to 2020.
scrrenshot.(at the right side of the screen.)
Screenshot (152)

### PR DESCRIPTION
**Pull request by SuryanshShahi**
Fixes #50

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
Please revert other formatting changes.

**Comment by SuryanshShahi** [comment]
@snitin315 now, is it ok?

**Comment by SuryanshShahi** [comment]
@snitin315 now, is it ok?

**Comment by snitin315** [comment]
I can still see `+1349 -815` changes

**Pull request closed without merging**
