### PR TITLE
change the year from 2019 to 2020.

### PR DESCRIPTION
**Pull request by Chaitanyassr**
fix issue #50 
### Before:
Screenshot (152)

### After:
Screenshot (153)

### CODE REVIEW

**Comment by snitin315** [comment]
Squash your commits , you have 7 commits for `+1` change only.

**Comment by snitin315** [comment]
Also the issue no. is linked in PR description not in PR title, 
add `Fixes #50 ` in your description and remove it from Title.

**Comment by snitin315** [comment]
@shivaylamba @edjustice @HeinKhantZaw please review PR's carefully.

**Comment by Chaitanyassr** [comment]
> Why adding an image file?

Elastic.png is already there in the main branch, i m not adding it. I did this pr long ago and after that Elastic.png was added. i merged the new changes made by the new PR(6th commit) and after that it started showing.

**Comment by snitin315** [comment]
please rebase your branch and then squash the commits.

**Comment by Chaitanyassr** [comment]
> please rebase your branch and then squash the commits.

cloning the forked repo results in chaging the img file name(lowercase to uppercase). i m unable to rebase as local changes need to be commit first and doing so will leads to another change in image file.

**Comment by snitin315** [comment]
If you are having trouble in reading just reset your branch. As this is a very minor change .

First abort if any rebase in process ,
`git rebase --abort`

```
git pull --rebase upstream master

git reset --hard upstream/master

```

**Pull request closed without merging**
