### PR TITLE
Fix map in mobile view

### PR DESCRIPTION
**Pull request by MuhammadWasif**
Map is not showing in mobile view.
Here's the deployment link: https://wasif.codes/summit.fossasia.org/

> Sorry for extra changes. My code editor automatically performs that following best practices

### CODE REVIEW

**Comment by kushthedude** [comment]
This is how it is showing now 
Screenshot 2020-01-03 at 11 34 38 PM

Fix it please .

**Comment by Dishebh** [comment]
@MuhammadWasif Any progress on this one?

**Comment by MuhammadWasif** [comment]
@dishebh not actually. Due to some other work I'm too busy these days to contribute to open source. You can take over this if you want

**Comment by Dishebh** [comment]
@MuhammadWasif I guess the issue is resolved now.

**Pull request closed without merging**
