### PR TITLE
Added Elastic, Instaclustr & Proudy supported by Section

### PR DESCRIPTION
**Pull request by jatin2003**
- [x] Included a description of the change below.

## Changes done in this Pull Request Fixes:-

- Issue https://github.com/fossasia/summit.fossasia.org/issues/41
- Issue https://github.com/fossasia/summit.fossasia.org/issues/45
- Issue https://github.com/fossasia/summit.fossasia.org/issues/46

## Description / Changes:-

I have added Elastic as Bronze Sponsor, Instaclustr as Silver Sponsor & also added 'Proudly supported by' Section

### CODE REVIEW

**Comment by NishithP2004** [comment]
Dude I just created a PR at the same time 😂

**Comment by jatin2003** [comment]
@edenyay Review.

**Comment by kushthedude** [comment]
Changes are clashing with other PR, revert the changes which are overlapping and just add the proudly supported section in thus PR.
Also provide a deployment link for the same.

**Comment by hpdang** [comment]
thank you @jatin2003

**Comment by DanteFrank** [comment]
Awesome contribution Jatin

**Comment by jatin2003** [comment]
Thanks @DanteFrank

**Pull request merged**
